version: "3.8"
services:
  db:
    image: postgres:16
    container_name: chat-postgres
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chatpwd
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat -d chatapp"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  db-data:
