spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chatapp}
    username: ${DB_USERNAME:chat}
    password: ${DB_PASSWORD:chatpwd}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:change-me-please-32bytes-min}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
