spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: chat
    password: chatpwd

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
